name: Secret Scan

on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: ${{ github.repository }}
      ref:
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Run TruffleHog on last 20 commits
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --fail --results=verified,unknown
